import { z } from 'zod';

/** Tope de un identity token de Apple (en la práctica ~1 KB); evita parsear basura enorme. */
const IDENTITY_TOKEN_MAX = 8192;
const NONCE_MAX = 256;
const NOMBRE_MAX = 200;

/**
 * Request contract for `POST /api/auth/apple/token`.
 *
 * - `identityToken`: el JWT que entrega Apple en la autorización nativa.
 * - `nonce`: el nonce CRUDO que generó la app; Apple recibió su SHA-256 y lo
 *   copió al claim `nonce` del token (el servidor lo hashea y compara).
 * - `nombre`: nombre completo, SOLO en la primera autorización (Apple no lo
 *   incluye en el token). `null`/ausente en los logins siguientes.
 *
 * A diferencia del contrato de Google, este esquema SÍ se parsea en la ruta
 * (`safeParse`), pero una forma inválida no produce 400: toma el mismo 401
 * genérico que cualquier otro fallo (no enumeración).
 */
export const authAppleTokenRequestSchema = z.object({
  identityToken: z
    .string()
    .min(1)
    .max(IDENTITY_TOKEN_MAX)
    .describe('Apple identity token (JWT) from the native authorization.'),
  nonce: z
    .string()
    .min(1)
    .max(NONCE_MAX)
    .describe(
      'Raw nonce generated by the app. The app passes its SHA-256 (hex) to Apple; the server hashes this value and compares it with the token nonce claim.',
    ),
  nombre: z
    .string()
    .max(NOMBRE_MAX)
    .nullish()
    .describe(
      'Full name, only available on the FIRST authorization (Apple never puts it in the token). Omit or null afterwards.',
    ),
});
